import "@/styles/globals.css";

import type { Metadata } from "next";

import {
  SidebarProvider,
} from "@/components/ui/sidebar";

import { AppSidebar } from "@/components/AppSidebar";


export const metadata: Metadata = {
  title: "Fefe3d printing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/fefe.webp" type="image/webp" />
      </head>
      <body className={` antialiased`}>
        <SidebarProvider className="h-screen">
          <AppSidebar />
      <main>
        {children}
      </main>
    </SidebarProvider>
      </body>
    </html>
  );
}
